### ISSUE TITLE
Undeclared dependency on DB_File

### ISSUE THREAD

**Issue by andk** [skx/WebService--Amazon--Route53--Caching#1]
As per subject. Grep:

http://search.cpan.org/grep?release=WebService-Amazon-Route53-Caching-0.4.1;string=DB_File;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/45602758

HTH&&Thanks,

**Comment by skx** [comment]
I should have seen that directly; sorry for missing it.

**Comment by skx** [comment]
Release 0.4.2 has now been uploaded to CPAN, and should be visible within the next few hours.
